spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/urlshortener
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
